version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_username
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
  codingtask:
    image: ${DOCKER_REGISTRY-}codingtask
    build:
      context: .
      dockerfile: CodingTask/Dockerfile
    ports:
       - "8080"       
    depends_on:
      - postgres
